spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coursecompass
    username: mavhinamulisa
    password: Mu6854##
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 30MB
