spring.application.name=coursecompass

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.FilterChainProxy=DEBUG

spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=30MB

resend.api.key=re_7Xodc9j6_QK59gtNRXdj2fBzfQvJTDWFn

spring.jpa.hibernate.ddl-auto=update